INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('staff', 'password','Tan Ming Ming', 'tanmingming@email.com', '62001211', 1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('boss', 'password','Boss Lim', 'bosslim@email.com', '62001231', 1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('aaronwee','password','Aaron Wee','aaronwee@email.com','62111126',1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('abigaildesouza','password','Abigail de Souza','abigaildesouza@email.com','62113010',1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('adilahmohamad','password','Adilah Mohamad','adilahmohamad@email.com','62115521',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('adlinakhoo','password','Adlina Khoo','adlinakhoo@email.com','62116566',15);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('alexiswoo','password','Alexis Woo','alexiswoo@email.com','62115050',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('angsoohoonnicole','password','Ang Soo Hoon Nicole','angsoohoonnicole@email.com','62116687',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('aqilyacob','password','Aqil Yacob','aqilyacob@email.com','62112708',16);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('bettytoy','password','Betty Toy','bettytoy@email.com','62117158',16);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('bolow','password','Bo Low','bolow@email.com','62113340',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('briangovindasamy','password','Brian Govindasamy','briangovindasamy@email.com','62115005',12);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('candiceyu','password','Candice Yu','candiceyu@email.com','62116836',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('cassandrapeh','password','Cassandra Peh','cassandrapeh@email.com','62117281',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('chiaweekeongcharles','password','Chia Wee Keong Charles','chiaweekeongcharles@email.com','62117890',15);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('christinagan','password','Christina Gan','christinagan@email.com','62114230',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('colbysng','password','Colby Sng','colbysng@email.com','62111827',17);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('cyrilquek','password','Cyril Quek','cyrilquek@email.com','62118127',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('danielnordin','password','Daniel Nordin','danielnordin@email.com','62117283',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('davidkok','password','David Kok','davidkok@email.com','62119261',18);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('dorachew','password','Dora Chew','dorachew@email.com','62116609',8);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('douglaskhoo','password','Douglas Khoo','douglaskhoo@email.com','62113403',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('eleanoresoh','password','Eleanore Soh','eleanoresoh@email.com','62115424',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('ethankumar','password','Ethan Kumar','ethankumar@email.com','62112511',5);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('feliciakhoo','password','Felicia Khoo','feliciakhoo@email.com','62111734',3);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('garrycheah','password','Garry Cheah','garrycheah@email.com','62119089',4);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('garthwijeysingha','password','Garth Wijeysingha','garthwijeysingha@email.com','62114657',1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('geneho','password','Gene Ho','geneho@email.com','62116840',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('gladysbenjamin','password','Gladys Benjamin','gladysbenjamin@email.com','62118215',6);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('grahampillai','password','Graham Pillai','grahampillai@email.com','62117667',7);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('hafizahlow','password','Hafizah Low','hafizahlow@email.com','62115320',9);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('hanwenqiangotis','password','Han Wenqiang Otis','hanwenqiangotis@email.com','62117473',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('hermansng','password','Herman Sng','hermansng@email.com','62111492',16);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('hudsonsun','password','Hudson Sun','hudsonsun@email.com','62111978',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('jakelau','password','Jake Lau','jakelau@email.com','62119486',4);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('jeanniekee','password','Jeannie Kee','jeanniekee@email.com','62119091',3);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('jeannielau','password','Jeannie Lau','jeannielau@email.com','62112913',9);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('joshuachan','password','Joshua Chan','joshuachan@email.com','62118045',8);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('juliakoh','password','Julia Koh','juliakoh@email.com','62117960',6);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('kellyyu','password','Kelly Yu','kellyyu@email.com','62112819',19);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('khorbeechin','password','Khor Bee Chin','khorbeechin@email.com','62111892',5);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('kimang','password','Kim Ang','kimang@email.com','62116308',19);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('kimberlyphua','password','Kimberly Phua','kimberlyphua@email.com','62116147',6);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('kurtisfong','password','Kurtis Fong','kurtisfong@email.com','62116089',19);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('kwokaimeielmira','password','Kwok Ai Mei Elmira','kwokaimeielmira@email.com','62116913',4);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('lancemok','password','Lance Mok','lancemok@email.com','62111316',6);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('lauraooi','password','Laura Ooi','lauraooi@email.com','62118946',16);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('laurawoo','password','Laura Woo','laurawoo@email.com','62117104',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('leliachang','password','Lelia Chang','leliachang@email.com','62112695',17);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('leonardkang','password','Leonard Kang','leonardkang@email.com','62114326',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('lewiswee','password','Lewis Wee','lewiswee@email.com','62119576',15);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('limkhimtiangluna','password','Lim Khim Tiang Luna','limkhimtiangluna@email.com','62119546',18);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('lindachee','password','Linda Chee','lindachee@email.com','62111066',14);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('lingngiaphengmervin','password','Ling Ngiap Heng Mervin','lingngiaphengmervin@email.com','62114262',6);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('lunaseow','password','Luna Seow','lunaseow@email.com','62114788',6);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('malcolmthomas','password','Malcolm Thomas','malcolmthomas@email.com','62112551',1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('margaretkoh','password','Margaret Koh','margaretkoh@email.com','62115361',18);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('mariamsaat','password','Mariam Saat','mariamsaat@email.com','62118785',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('martinloh','password','Martin Loh','martinloh@email.com','62112806',5);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('michellepang','password','Michelle Pang','michellepang@email.com','62115539',14);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('mindyfong','password','Mindy Fong','mindyfong@email.com','62118137',4);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('mohammadwahid','password','Mohammad Wahid','mohammadwahid@email.com','62118675',10);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('morgantoh','password','Morgan Toh','morgantoh@email.com','62111697',5);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('nadiaquek','password','Nadia Quek','nadiaquek@email.com','62117463',19);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('naimahnasar','password','Naimah Nasar','naimahnasar@email.com','62119809',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('najahsaat','password','Najah Saat','najahsaat@email.com','62117426',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('neillow','password','Neil Low','neillow@email.com','62115409',4);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('nellechiasoohoon','password','Nelle Chia Soo Hoon','nellechiasoohoon@email.com','62115233',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('ngiamkokweeaaron','password','Ngiam Kok Wee Aaron','ngiamkokweeaaron@email.com','62111488',17);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('ngiammingguidemond','password','Ngiam Ming Gui Demond','ngiammingguidemond@email.com','62112484',8);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('nicolewee','password','Nicole Wee','nicolewee@email.com','62113465',6);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('ongweiquankeith','password','Ong Wei Quan Keith','ongweiquankeith@email.com','62116686',4);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('oswaldofongweijie','password','Oswaldo Fong Weijie','oswaldofongweijie@email.com','62118693',17);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('otiskhor','password','Otis Khor','otiskhor@email.com','62117663',1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('phyllisfang','password','Phyllis Fang','phyllisfang@email.com','62111977',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('preetiho','password','Preeti Ho','preetiho@email.com','62119293',1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('raheemsaat','password','Raheem Saat','raheemsaat@email.com','62113933',16);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('randalyip','password','Randal Yip','randalyip@email.com','62114759',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('rebeccateh','password','Rebecca Teh','rebeccateh@email.com','62116646',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('robinlee','password','Robin Lee','robinlee@email.com','62117007',7);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('rodgerfang','password','Rodger Fang','rodgerfang@email.com','62115156',17);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('sarahlee','password','Sarah Lee','sarahlee@email.com','62119950',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('selinalow','password','Selina Low','selinalow@email.com','62112205',13);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('shawnteo','password','Shawn Teo','shawnteo@email.com','62114134',5);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('spencersmith','password','Spencer Smith','spencersmith@email.com','62114018',16);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('sterlingkee','password','Sterling Kee','sterlingkee@email.com','62118512',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('suzannequek','password','Suzanne Quek','suzannequek@email.com','62114873',5);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('sylviajeyaretnam','password','Sylvia Jeyaretnam','sylviajeyaretnam@email.com','62116919',3);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('tehsiewwei','password','Teh Siew Wei','tehsiewwei@email.com','62112559',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('teohlayhean','password','Teoh Lay Hean','teohlayhean@email.com','62119529',19);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('thaqifmohamed','password','Thaqif Mohamed','thaqifmohamed@email.com','62116710',15);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('thiaboonhowbrandon','password','Thia Boon How Brandon','thiaboonhowbrandon@email.com','62116742',3);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('thiachorping','password','Thia Chor Ping','thiachorping@email.com','62119435',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('travisdanker','password','Travis Danker','travisdanker@email.com','62118673',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('trevorzhou','password','Trevor Zhou','trevorzhou@email.com','62119673',14);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('vicentesi','password','Vicente Si','vicentesi@email.com','62112662',11);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('williampoon','password','William Poon','williampoon@email.com','62117140',10);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('xavierlamweishaun','password','Xavier Lam Wei Shaun','xavierlamweishaun@email.com','62113465',7);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('yaovoonnoh','password','Yao Voon Noh','yaovoonnoh@email.com','62115176',1);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('yapteesengcasey','password','Yap Tee Seng Casey','yapteesengcasey@email.com','62118763',2);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('yusoosee','password','Yu Soo See','yusoosee@email.com','62119803',20);
INSERT INTO employees (username, password, staff_name, staff_email, staff_phone, organisation_id) VALUES ('yvonneteo','password','Yvonne Teo','yvonneteo@email.com','62113199',5);

INSERT INTO manager_staff(staff_id, manager_id) VALUES (1, 2);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (2, 2);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (3, 2);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (4, 2);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (5, 2);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (6, 2);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (7, 2);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (8, 2);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (9, 1);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (10, 1);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (11, 1);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (12, 1);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (13, 1);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (14, 1);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (15, 1);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (16, 3);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (17, 3);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (18, 3);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (19, 3);
INSERT INTO manager_staff(staff_id, manager_id) VALUES (20, 3);

INSERT INTO organisations(organisation_name) VALUES ('Govtech');
INSERT INTO organisations(organisation_name) VALUES ('Ministry of Manpower');
INSERT INTO organisations(organisation_name) VALUES ('Ministry of Finance');
INSERT INTO organisations(organisation_name) VALUES ('Ministry of Education');
INSERT INTO organisations(organisation_name) VALUES ('Infocomm Media Development Authority');
INSERT INTO organisations(organisation_name) VALUES ('Central Provident Fund Board');
INSERT INTO organisations(organisation_name) VALUES ('Professional Engineers Board');
INSERT INTO organisations(organisation_name) VALUES ('Ministry of Health');
INSERT INTO organisations(organisation_name) VALUES ('The Istana');
INSERT INTO organisations(organisation_name) VALUES ('Family Justice Courts');
INSERT INTO organisations(organisation_name) VALUES ('State Courts');
INSERT INTO organisations(organisation_name) VALUES ('Singapore Parliament');
INSERT INTO organisations(organisation_name) VALUES ('Supreme Court');
INSERT INTO organisations(organisation_name) VALUES ('PSC	Supreme Court	Organs of State');
INSERT INTO organisations(organisation_name) VALUES ('Urban Redevelopment Authority');
INSERT INTO organisations(organisation_name) VALUES ('Land Transport Authority');
INSERT INTO organisations(organisation_name) VALUES ('National Arts Council');
INSERT INTO organisations(organisation_name) VALUES ('Housing and Development Board');
INSERT INTO organisations(organisation_name) VALUES ('Ministry of Foreign Affairs');


INSERT INTO leave (staff_id, leave_type, manager_id, date_start, date_end, days_count, request_status, created_at, updated_at)
VALUES (2, 'medical leave', 2, '2019-08-01', '2019-08-03', 1, 'submitted', '2019-08-02 10:00:09', '2019-08-02 10:00:09') ;
